version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config
    networks:
      - netlab

  suricata:
    image: jasonish/suricata
    container_name: suricata
    cap_add:
      - NET_ADMIN
    command: -i eth0
    volumes:
      - ./suricata:/etc/suricata
      - ./logs/suricata:/var/log/suricata
    depends_on:
      - mosquitto
    networks:
      - netlab

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/suricata:/var/log/suricata:ro
    networks:
      - netlab

networks:
  netlab:
    driver: bridge
